### ISSUE TITLE
Could you please share the images and ground truths?

### ISSUE THREAD

**Issue by KangLeeShaw** [imadgohar/DTU-annotations#1]

**Comment by imadgohar** [comment]
The images are publicly available on Mendely, download them and visualize bboxes to get the GT.

**Comment by KangLeeShaw** [comment]
> The images are publicly available on Mendely, download them and visualize bboxes to get the GT.

Thank you for your reply and your work.  I'm a freshman in the research about the wind turbine blade and I don't know Mendely so I searched it and the result is a citation management tool. So could you please share the website or something?

**Comment by imadgohar** [comment]
https://data.mendeley.com/datasets/hd96prn3nc
The link to the images.

**Comment by KangLeeShaw** [comment]
> https://data.mendeley.com/datasets/hd96prn3nc The link to the images.

Cool, thank you so much.
