### ISSUE TITLE
Can we have your Image slicing script?

### ISSUE THREAD

**Issue by ThibautLucas** [imadgohar/DTU-annotations#2]
Hi there 👋 

I would like to reproduce your results, 
However I'm unable to understand your overlapped slicing method (I read your paper) 
Could provide further explainations or the slicing script please? 

Have a nice day

**Comment by Domandrenog** [comment]
Hey! Where is the paper?

**Comment by davideCremona** [comment]
The paper is this one: https://www.mdpi.com/2075-1702/11/10/953

**Comment by Raozey** [comment]
I have the same doubt too, maybe you can kindly provide some code of slicing @davideCremona

**Comment by davideCremona** [comment]
I am not the writer of the paper nor the developer of this repo :)

**Comment by Raozey** [comment]
> I am not the writer of the paper nor the developer of this repo :)

Sry about that, but we can communicate, can you leave an email?

**Comment by imadgohar** [comment]
Read the paper in detail all the information is there.
https://www.mdpi.com/2075-1702/11/10/953
