### ISSUE TITLE
Can you share scripts or instructions to visualize the annotations?

### ISSUE THREAD

**Issue by davideCremona** [imadgohar/DTU-annotations#3]

**Comment by imadgohar** [comment]
The images are available publicly. The details are given in the paper and the link is also provided. Please read the paper for details.
https://www.mdpi.com/2075-1702/11/10/953

**Comment by Raozey** [comment]
@davideCremona @imadgohar The visualization seems need pay more attention to the overlap, and you can refer to the SAHI model which can do the slice automatically.
